package org.grails.plugins.google.visualization

import static org.junit.Assert.*

import grails.test.GrailsUnitTestCase
import grails.test.mixin.support.*
import grails.test.mixin.web.GroovyPageUnitTestMixin

/**
 * It checks a javascript code generated by GoogleVisualizationTagLib.
 */
@TestMixin(GroovyPageUnitTestMixin)
class GoogleVisualizationTagLib2Tests {

    void setUp() {
    }

    void tearDown() {
    }

    void testIntensityMap() {
		mockTagLib(GoogleVisualizationTagLib)
		def columns = [['string', 'Country'], ['number', 'Number']]
		def data = [['US', 4357], ['DE', 5201]]
		def colors = ['ffff00']
		assertOutputEquals ("\n"
				+ "\n"
				+ "\n"
				+ "<script type=\"text/javascript\">\n"
				+ "    google.load('visualization', '1', {'packages': ['intensitymap']});\n"
				+ "    google.setOnLoadCallback(drawMap);\n"
				+ "    \n"
				+ "    function drawMap() {\n"
				+ "        map_data = new google.visualization.DataTable();\n"
				+ "        \n"
				+ "        map_data.addColumn('string', 'Country');\n"
				+ "        \n"
				+ "        map_data.addColumn('number', 'Number');\n"
				+ "        \n"
				+ "        \n"
				+ "        map_data.addRow(['US', 4357]);\n"
				+ "        \n"
				+ "        map_data.addRow(['DE', 5201]);\n"
				+ "        \n"
				+ "      \n"
				+ "        map = new google.visualization.IntensityMap(document.getElementById('map'));\n"
				+ "\n"
				+ "        \n"
				+ "\n"
				+ "\n"
				+ "\n"
				+ "        \n"
				+ "        map.draw(map_data, {colors: ['ffff00'], height: 150, width: 150});\n"
				+ "\n"
				+ "        \n"
				+ "    }\n"
				+ "</script>"
				, '<gvisualization:intensityMap name="map" elementId="map" columns="${columns}" data="${data}" colors="${colors}" height="${150}" width="${150}"/>'
				, [columns : columns, data : data, colors : colors]
			)
    }
}
